default: &default
  cluster: "test-cluster"
  task: "test-task"
  security-group: "sg1"
  subnet: "subnet-54321"
  cmd:
    - bash
    - -c
    - echo
    - "hello world"

custom:
  <<: *default
  subnet: "subnet-12345"
  cmd:
    - bash
    - -c
    - echo
    - "custom"
